### ISSUE TITLE
Add new functionality if possible

### ISSUE THREAD

**Issue by technophyle66** [technophyle66/real-time-chat#16]

**Comment by Yash-RajSingh** [comment]
> _No description provided._

Hey, do you have any functionality in mind that you'd like to be added in the project?

**Comment by technophyle66** [comment]
@Yash-RajSingh How about the ability send message by pressing Enter Key? Right now the app only allows sending messages by pressing the "Send Message" key

**Comment by Yash-RajSingh** [comment]
> @Yash-RajSingh How about the ability send message by pressing Enter Key? Right now the app only allows sending messages by pressing the "Send Message" key

Sure I'll try to implement that.  Is there anything else that I need to know about the project setup?

**Comment by technophyle66** [comment]
No! Just be sure to read CONTRIBUTING.md and README.md to check how you can run the app on your device and you should be fine!

**Comment by Yash-RajSingh** [comment]
> No! Just be sure to read CONTRIBUTING.md and README.md to check how you can run the app on your device and you should be fine!

Great I'll try to implement that feature as soon as possible and get back to you!

**Comment by Yash-RajSingh** [comment]
> @Yash-RajSingh How about the ability send message by pressing Enter Key? Right now the app only allows sending messages by pressing the "Send Message" key

Hey @technophyle66 , I've implemented this feature in the PR #29 . Kindly please review the change and let me know if there are any changes required.

**Comment by technophyle66** [comment]
Awesome! Great work @Yash-RajSingh, the functionality is there and working, closing the issue.
